### PR TITLE
Some minor improvements to go-steamapi

### PR DESCRIPTION
**Pull request by fasmat**
I added the licence file and functions to convert between different SteamID formats. The next thing I'll start working on will be game specific api calls.

### CODE REVIEW

**Comment by Philipp15b** [comment]
Thanks a lot for the pull request. I've got some points about the last commit (8c02e00) though: 
- You mention that some API calls require 32bit Steam IDs and some 64bit. Could you clarify that? Are there some calls already implemented in a wrong way? 
- Maybe it would make sense then to change all existing APIs to use the new SteamID type even if that would be a breaking change.
- And since all API calls use only numbers, I think the SteamID should be just an `uint64`.
- Is there a reason the `steamid` struct itself is not exported?

For now, I'm going to merge the first three commits.

**Comment by fasmat** [comment]
Thank you for accepting the request =).

I'm working on implementing dota specific queries like http://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/v1 this weekend, if I have enogh time. At least this call requires an 32-bit account id. I used https://developer.valvesoftware.com/wiki/SteamID as a reference for conversation between different forms of the steam ID and tested my code if it gives the correct values for my account (double checked with sample calls to the api and http://steamidconverter.com/fasmat).

To avoid breaking the api I created the steamid struct which has .As32Bit() .As64Bit() and .String() so you just need to create a steamid once and call the api functions with the corresponding representation.

**Comment by fasmat** [comment]
As promised, I added what I could this weekend. There are still some API calls missing, but they will follow soon.

**Comment by fasmat** [comment]
Hi, still working on the steam api? :-)

**Comment by Philipp15b** [comment]
Sorry it took a (very very long) while, but I'll merge this now. Thanks a lot! 👍

**Pull request merged**
